### ISSUE TITLE
Implement representation of paradigm cells for certain inflected forms that do not exist for a lemma

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#111]
Should we just remove that part of the paradigm table instead of showing blanks @aarppe 

![Screenshot from 2019-09-25 10-31-08](https://user-images.githubusercontent.com/44753941/65620958-09848b00-df80-11e9-8c77-e634fda60950.png)

**Comment by aarppe** [comment]
This is an extreme case where certain inflected forms are not possible. If a word is already a diminutive, you cannot apply again diminutivization on it. A similar case are verbs that can only be used in plural form (so they always require a plural subject, like 'they do X'.

The idea is that in such cases we present an empty cell, or better yet, em-dashes, to indicate that the particular lemma does not have those forms.

**Comment by eddieantonio** [comment]
My opinion, @aarppe, is that if there are no inflections in an entire "panel" (e.g.., Diminutive, and Diminutive Possession), then that panel should be omitted entirely, perhaps with a message saying "these inflections are not possible!"

**Comment by aarppe** [comment]
1. If it's an empty cell in a row otherwise with word forms, then we just show an em-dash or equivalent.

2. If it's an entire block of empty rows, like when no diminutive forms are shown for nouns which are already diminutives, then we could just not show the whole block. Maybe in such a case there could be a note such as 'No diminutive forms'.

3. If it's an occasional empty row, as is the case with with singular only verbs such as certain VIIs (like mispon) or dependent nouns (like nôhkom), then we should show that those rows  (or cells) are empty with em-dashes.

The distinction between 2 and 3 is clear when the paradigms are ordered so that the empty rows are surrounded by full rows. If the paradigm concerns a verb such as nôtinitowak 'they fight each other/one another' or if the paradigm would be organized as 'it > it (further) > they > they (further), then we potentially run into a problem as we would have two or more empty rows next to each other. Would we then not show explicitly that those rows are empty, because that is useful information to the language learner? In my view I'd be tempted to show empty cells (with em-dashes) in case 3, but leave out the whole block in case 2 (which I think only applies to pre-diminutivized nouns).

**Comment by aarppe** [comment]
@kobexamoh This is something that just should be simply done.

Currently, we only present the basic paradigms that have single columns. Thus, we could simply present an em-dash when a particular inflected word form is missing, as the case when entire blocks are missing primarily concerns the various inflected diminutive forms that are not covered in the basic layouts. Therefore, we can leave as a separate later issue when we'd not show at all such entire blocks of missing inflected wordforms.

**Comment by aarppe** [comment]
@kobexamoh In #169, we are leaving out the possessed diminutive blocks from even full noun layouts. Thus, what is left as potentially empty cells are individual ones, e.g. plural forms of singular-only verbs and singular forms of plural-only verbs. In such a case, we would want to show a horizontal line, instead of an empty/blank cell.

**Comment by eddieantonio** [comment]
> @kobexamoh In #169, we are leaving out the possessed diminutive blocks from even full noun layouts. Thus, what is left as potentially empty cells are individual ones, e.g. plural forms of singular-only verbs and singular forms of plural-only verbs. In such a case, we would want to show a horizontal line, instead of an empty/blank cell.

@aarppe, could you please provide a few examples of this? I think one is [mispon](https://sapir.artsrn.ualberta.ca/cree-dictionary/word/mispon/):

![Screen Shot 2020-06-23 at 8 41 27 AM](https://user-images.githubusercontent.com/2294397/85417925-6f14a080-b52d-11ea-82f6-d6aa3220c5ea.png)

**Comment by aarppe** [comment]
Yes, _mispon_ is a singular-only VII. As for a plural-only VAI, an examply would be _nôtinitowak_. 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/15003407/85449555-1e18a280-b555-11ea-9dd5-b1ac7c85a934.png">

An example of a dictionary entry/lemma that shouldn't get a diminutive because the lemma is already diminutivized is _sîsîpisis_: 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/15003407/85450177-c3337b00-b555-11ea-9f17-4628b31c4a4e.png">

The full NA paradigm also indicates that the cells for the non-obviated third-person possessor forms are empty.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/15003407/85450350-ea8a4800-b555-11ea-821e-edd096cf6bf9.png">

Finally, _nôhkom_ is a case where the unspecified possessor is not possible:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/15003407/85450619-2f15e380-b556-11ea-899f-df8d9e47999c.png">

Here, I would explicitly indicate with an em-dash or the like that the singular (or other) forms are missing, rather than leaving those cells or rows out.

**Comment by eddieantonio** [comment]
Consider _hiding_ empty paradigms instead of using an —

**Comment by aarppe** [comment]
@kobexamoh This is what we wanted mock-ups for alternative solution. Currently, I do want to see that the missing cells are shown rather than visually excluded, but how the missingness can be shown (em-dash, graying, etc.) should be explored.

**Comment by aarppe** [comment]
@Madoshakalaka Let's make an executive decision, that a) missing cells in a paradigm that are not possible for any lemma for that paradigm are marked as a _greyed out cell_, and b) missing forms that are not possible for a particular lemma but are possible for that form are marked with an **em-dash**. I can imagine that these strategies could be reversed, but let us go with this scheme for now.

How these can be identified is that 1) a-cells do not have an FST specification in the layouts (so the cell is literally empty), whereas 2) b-cells do have an FST specification in the layouts, but the FST does not produce the applicable form for some particular lemma.

**Comment by aarppe** [comment]
@Madoshakalaka Seems to me this is done?
