### ISSUE TITLE
Refine ranking for fuzzy matching

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#113]
In the goal of _progressive enhancement_, let's disable the Levenshtein distance fuzzy search. Fuzzy matching the way itwêwina does is fine for now.

@aarppe, could you provide your example of when this is a problem?

Later on, we'll need to adjust the edit distance calculation, but that's a future TODO!

**Comment by Madoshakalaka** [comment]
It's easy to turn off fuzzy search. What is the bug though?

**Comment by eddieantonio** [comment]
@aarppe says that some of the search results are DANGEROUSLY misleading.
Plus there is the possibility of having too many results. We don't yet have
a nice way of ranking the too many results, so it's better to just turn off
fuzzy search for now. The bug is that fuzzy search is on!

**Comment by Madoshakalaka** [comment]
Whoa. Sure! I'll turn it off.

**Comment by aarppe** [comment]
The main problem from the perspective of a naive user, the fuzzy search produced a lot of results, some of which were semantically funny, some repetitions (due to MD content, maybe), and then the lemma one was after might be quite a ways further down.

That does not induce confidence in newbie users (like Arok).

I think that this can be resolved by careful tuning of the fuzzy distance calculator (including edit distance with different costs for different edits, lemma frequency, and other stuff), but we need to come up with the weights (I'd suggest using an adaptation of those from the spell-checker) and start making use of the lemma-frequencies (we've got them), implement those in a trial version, and then test how that works.

But now, e.g. searching with ninipan, I get both nipâw 'sleep' and nipiw 'die'.

Of course, ed(â,a) and ed(â,i) is =1 is the same, but here, and in some other trials, the results, if not ordered according to some though-through metrix, are not good.

Eddie has written some tentative guidelines about what the weighting could be, pretty much similar to the spell-checker weighting.

ls ~/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/*.default.txt
/Users/arppe/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/editdist.default.txt
/Users/arppe/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/final_strings.default.txt
/Users/arppe/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/initial_letters.default.txt
/Users/arppe/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/strings.default.txt
/Users/arppe/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/words.default.txt

**Comment by Madoshakalaka** [comment]
@aarppe No problem, looking forward to having fine tuned weights!

**Comment by aarppe** [comment]
Do note that we already have weights we could use in the above mentioned files.

In these files, the standard weight for a single-character change is 10. The files have smaller weights for single-character and multi-character changes that would be more auspicious, such as changing vowels to have diacritics for length (or not), excessive or missing -h- between vowels and stops, and some other common mistakes. So, one could already create character-string-based weighting of the edits.

This would yet exclude whole-lemma based weights, but those are ones we can add later.

**Comment by aarppe** [comment]
Here you go, with some tentative values, and before corpus-based lemma and other feature weights:

less ~/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/editdist.default.txt | gawk -F"\t" 'NF>=3' | gawk '{ print $1" -> "$2" : "$3; }'

a -> â : 2
e -> ê : 0
i -> î : 3
o -> ô : 3
g -> k : 8
d -> t : 8
j -> c : 8
g -> c : 9
â -> a : 4
î -> i : 4
ô -> o : 4
w -> y : 0
i -> ô : 4
a -> ê : 4

c,h -> h,c : 8
k,h -> h,k : 5

less ~/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/strings.default.txt | gawk '$0 ~ /^[^#]/ { split($1,s,":"); print s[1]" -> "s[2]" : "$2; }'
ch -> c : 0.5
ts -> c : 0.5
ahc -> ac : 1
ac -> ahc : 1
ihc -> ic : 1
ic -> ihc : 1
ohc -> oc : 1
oc -> ohc : 1
âhc -> âc : 1
âc -> âhc : 1
êhc -> êc : 1
êc -> êhc : 1
îhc -> îc : 1
îc -> îhc : 1
ôhc -> ôc : 1
ôc -> ôhc : 1
ahk -> ak : 1
ak -> ahk : 1
ihk -> ik : 1
ik -> ihk : 1
ohk -> ok : 1
ok -> ohk : 1
âk -> âhk : 1
âhk -> âk : 1
êk -> êhk : 1
êhk -> êk : 1
îk -> îhk : 1
îhk -> îk : 1
ôk -> ôhk : 1
ôhk -> ôk : 1
aht -> at : 1
at -> aht : 1
iht -> it : 1
it -> iht : 1
oht -> ot : 1
ot -> oht : 1
ât -> âht : 1
âht -> ât : 1
êt -> êht : 1
êht -> êt : 1
ît -> îht : 1
îht -> ît : 1
ôt -> ôht : 1
ôht -> ôt : 1
ahp -> ap : 1
ap -> ahp : 1
ihp -> ip : 1
ip -> ihp : 1
ohp -> op : 1
op -> ohp : 1
âhp -> âp : 1
âp -> âhp : 1
êhp -> êp : 1
êp -> êhp : 1
îhp -> îp : 1
îp -> îhp : 1
ôhp -> ôp : 1
ôp -> ôhp : 1
ahc -> âc : 1
âc -> ahc : 1
ehc -> êc : 1
ihc -> îc : 1
îc -> ihc : 1
ohc -> ôc : 1
ôc -> ohc : 1
ahk -> âk : 1
âk -> ahk : 1
ehk -> êk : 1
ihk -> îk : 1
îk -> ihk : 1
ohk -> ôk : 1
ôk -> ohk : 1
ahp -> âp : 1
âp -> ahp : 1
ehp -> êp : 1
ihp -> îp : 1
îp -> ihp : 1
ohp -> ôp : 1
ôp -> ohp : 1
aht -> ât : 1
ât -> aht : 1
eht -> êt : 1
iht -> ît : 1
ît -> iht : 1
oht -> ôt : 1
ôt -> oht : 1
awê -> âwe : 2

less ~/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/final_strings.default.txt | gawk '$0 ~ /^[^#]/ { split($1,s,":"); print s[1]" -> "s[2]" : "$2; }'
owin -> iwin : 5
ow -> iw : 5
a -> â : 0
wak -> wa : 4
wa -> wak : 4
yak -> ya : 4
ya -> ywak : 4
wê -> wêw : 4
we -> wêw : 4
ah -> wa : 4

**Comment by Madoshakalaka** [comment]
@aarppe Thanks, I changed "bug" label to "feature" and I'll utilize the weights to rank spell relaxed matches.

**Comment by aarppe** [comment]
No problem. While the absolute scale numeric values of the weights for the typo-correction in the spell-checker source code (with 10 as the default, and effectively with a 0-10 range) could be discussed, I'd think that the relative values that are used for typo correction have received quite some thought, so could be used. Of course, they can be log-scaled etc., in particular when we'd combine them as some function with corpus-based lemma frequencies.

Ideally, we'd only have these values specified in one place (e.g. the spell-checking error model txt files) from where they could be extracted also for weighting for the fuzzy input for itwêwina. Of course, the representation of the error-correction pairs varies somewhat for the different correction types with their distinct txt files ...

On the longer term, I think we might come of with an even more elaborate, multivariable weighting scheme, that might be in part derived from normal and typo corpus materials (when we accumulate the latter), but that would be for the stage after the next stage.

**Comment by aarppe** [comment]
To be explored: can the speller-hfst, i.e. the archive crk.zhfst, be used for this? (which combines an acceptor and an error-correction model)

This spell-checker error correction model already incorporates weightings for various edits, features, and lemmas, for the entire computational model, not just the forms in the paradigms. 

See: tools/spellcheckers/fstbased/desktop/hfst/Makefile.in

See: hfst-ospell -S tools/spellcheckers/fstbased/desktop/hfst/crk.zhfst
(INPUT: ninipan)
OUTPUT:
"ninipan" is NOT in the lexicon:
Corrections for "ninipan":
ninipân    5.079442
ninipin    13.079442
kinipân    15.079442
nôniyan    17.079441
nipipon    23.079441
ninipîs    23.079441
ninipîm    23.079441
kinipin    23.079441
ninipiy    23.079441
niwâpan    23.079441
nipiyan    23.079441

**Comment by aarppe** [comment]
This issue has a lot of overlap with #221.

**Comment by andrewdotn** [comment]
Edit distance is currently used as one input into the ranking function. I believe that this relates to the previous idea of what fuzzy search was or was meant to be?

**Comment by andrewdotn** [comment]
Actually this issue relates to a feature request for a new general fuzzy search feature that finds relevant results even when the entry is not analyzable by the spell-relaxed analyzer. So not just for ranking results, but for finding results by closeness to all entries in the dictionary. This could possibly use hfst-ospell.

One example could be, say, a bad typo like `qwapanrw` for `wâpamêw`.
