### ISSUE TITLE
Use a better example on the front page than "they habitually go on very large hunts"

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#150]
Right now, as an example of a "complicated word", we have this example: "ê-mâh-misi-nâh-nôcihikocik". I'm pretty sure we got this from some of Arok's materials, but it's kind of... violent? I don't feel like it's something we'd want to have on the front page 😅

Any ideas, @aarppe?

**Comment by aarppe** [comment]
Just to get the gears rolling, I pulled out a selection of complex forms. My favorites would be:

- _iyâta-wâ-kakwê-pîkinikahwât_ 's/he vainly intended to try to hew something/one [animate] small'
- _nikî-nitawi-kiskinwahamâkosin_ 'I went away to go to school'
- _ê-kî-kâh-nitawi-kâh-kîmôci-kotiskâwêyâhk_ 'you and we would go very secretly in full gallop'

And then a longer exposition of how one can extract these - maybe we should circulate some selected example words, rather than having just one.

1. Some often-used longer words:

- nikî-nitawi-kiskinwahamâkosin (from Sol Ratt's Dog Biscuits)
- nikî-nitawi-wâpamâw (a more common form from the A-W corpus)

2. The Bloomfield corpus has some nice ones:

```
cat ~/Google\ Drive/CreeFST/Bloomfield/bloomfield_MGS.vrt | gawk '{ print gsub("[-]","-",$1), $1; }' | sort -k1,1nr | gawk '$1>=4'
4 kita-isi-kî-ohci-nipahikawiyahk
4 kâ-kî-nitawi-ay-asawâpiyit
4 kâ-kî-ohci-pê-sipwêhtêcik
4 kâ-pê-âpihta-kîsikâw-mîcisoyin
4 kâ-ôh-kâ-ka-kiyokêt
4 kâ-ôh-kî-pê-nakatitakok
4 kâ-ôh-mâh-misi-wanâtisicik
4 kâ-ôh-pê-ay-itohtêyan
4 kâ-ôh-wî-kakwê-wâpamitân
4 nika-kî-isi-kisiwâk-osâpamak
4 ta-kî-êcik-âni-miywêyimât
4 ê-kî-mâh-mâyi-itikot
4 ê-kî-pê-isi-ohpikihitocik
4 ê-pê-nâh-nitawi-asamât
4 ê-pê-wâh-ohci-sipwêhtêyan
4 ê-wî-kakwê-ka-kitotikot
4 ê-wî-kakwê-nihtâ-pimohtahkwêhât
4 ê-âta-itê-kâh-kitâtwâwi
4 ê-âta-wî-kakwê-iyinîhkahisot
```

Some selections:

- kâ-kî-nitawi-ay-asawâpiyit 's/he looks around, s/he looks out; s/he waits and watches' -> s/he who went repeatedly to look around'
- ê-wî-kakwê-nihtâ-pimohtahkwêhât 's/he makes s.o. shoot with bow and arrow' -> s/he will try to make someone skilled at shooting with bow and arrow'
- ê-kî-mâh-mâyi-itikot 's/he says thus to s.o.' -> S/he very wickedly said about him/her.' (maybe not he best)
- iyâta-wâ-kakwê-pîkinikahwât 's/he hews s.o. small' (with initial change on the lexical preverb ata- -> s/he vainly intended to try to hew something/one [animate] small)

3. And an extraction from the A-W corpus:

```
cat ~ /giella/art/corp/crk/ahenakew_wolfart_MGS_tab-sep-anls_freq-sorted.txt | gawk '{ print gsub("[-]","-",$2), $2; }' | sort -k1,1nr | head -20
9 ê-kî-is-âya-~-mâci-aya-~-miyo-kîsihihcik
8 nikî-pê-mî-~-mîc-~-mî-~-mowâyâhkik
8 ê-kî-ma-miyo-~-ma-miyo-wa-wîkihk
7 kâ-nitawi-kihc-âsotamâ-~-n-~-tohk
7 ê-kî-is-âya-~-is-~-ispayik
7 ê-kî-kâh-~-nitawi-kâh-kîmôci-kotiskâwêyâhk
7 ê-kî-mân-âya-~-kahkiyaw-kîkway-tôtamâsocik
7 ê-kî-~-mâna-~-naha-~-otinâyâhkwâw
6 kâ-kî-ita-ohci-mâci-na-nisitawêyimak
6 ê-kî-ay-is-~-ka-kîsîhtâyâhk
6 ê-kî-is-âya-~-isi-nihtâwiminakinikêcik
6 ê-kî-is-âyi-~-nâh-nakwâtât
6 ê-kî-misi-~-kakwâhyaki-misi-pôsihcikêyâhk
6 ê-kî-mâh-misi-nip-~-nipahât
6 ê-kî-mân-âya-~-nitaw-îtwêstamawakik
6 ê-kî-wâh-~-pê-kîs-îtâskonikêt
6 ê-kî-ôm-ôhci-êkâ-wa-wâpamât
5 k-âti-kakâyawâtis-~-kakâyaw-âyât
5 ka-kî-isi-~-is-ôhpikihâwasoyahk
5 kâ-kî-aya-~-nitaw-âtoskêyân
```

Of course, there are some repetitions and hesitations above.

**Comment by aarppe** [comment]
@katieschmirler Could you validate for us the English translation of _ê-kî-kâh-nitawi-kâh-kîmôci-kotiskâwêyâhk_, if that is more or less _'you and we would go very secretly in full gallop'_.

This seems to be in the Ahenakew-Wolfart collection in "piko kīkway ē-nakacihtāt: kēkēk otācimowina ē-nēhiyawastēki mitoni ē-āh-itwēt māna Cecila Masuskapoe / There’s Nothing She Can’t Do : Kēkēk’s Autobiography published in Cree (Chapter 4)", cf.

http://sapir.artsrn.ualberta.ca/korp/#corpus=wolfart_ahenakew,&search=word%7C%C3%AA-k%C3%AE-k%C3%A2h-~-nitawi-k%C3%A2h-k%C3%AEm%C3%B4ci-kotisk%C3%A2w%C3%AAy%C3%A2hk&page=0

Relooking at that example, it might that due to the hesitation the intended word were a bit simpler, perhaps _ê-kî-nitawi-kâh-kîmôci-kotiskâwêyâhk_?

**Comment by katieschmirler** [comment]
It does look like an error with the extra _kâh_-, so yes I would drop that. Also it's exclusive, so would just be "we (but not you)". I would say "we went to race very secretly" -- could be "gallop", but that seems from the dictionary entry to be the meaning when talking about an animal (though if people are racing horses, they're probably galloping).

**Comment by aarppe** [comment]
@katieschmirler Ok, _ê-kî-nitawi-kâh-kîmôci-kotiskâwêyâhk_ it is. Can you eventually check the English translation in Cecilia Masuskapoe's book, so that we can be more confident about what it means?

**Comment by aarppe** [comment]
![image](https://user-images.githubusercontent.com/15003407/74600156-8fe25c00-504a-11ea-9118-6244cf7e574a.png)

Eventually, we'll want more information on the reduplicated element, _kâh-_ (if that is actually reduplication), as well.

**Comment by katieschmirler** [comment]
That book doesn't have a translation, so we would need to check with a Cree speaker. Otherwise I just would have provided the translation from the book. I believe _kâh-_ is reduplication in this case, as I'm fairly certain the preverb _kâh_- is grammatical not lexical and so would likely not be so far into the preverb complex.
