### ISSUE TITLE
Source xml file lemma resolution: dimimutive forms and idiomatic lemma

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#176]
"ayiwinisa" is analysable. Yet the current version on Sapir does not show its paradigm table.

Also It's special as "ayiwinisa" (+N+I+Pl) should chosen as its lemma instead of "ayiwinis" (+N+I+Sg like most NI). Just like how the word "data" is more common that "datum" in English

**Comment by Madoshakalaka** [comment]
I went investigating. Unfortunately, this is caused by limited expert knowledge in our importing process.

Both ayiwinisa and ayiwinis can be interpreted as different NIs. Currently the importer can not resolve whether ayiwinisa is a inflection of the first one or the second one.

```
ayiwinisa 
ayiwinisa       ayiwinisa+N+I+Pl
ayiwinisa       ayiwin+N+I+Der/Dim+N+I+Pl

ayiwinis 
ayiwinis        ayiwinisa+N+I+Sg
ayiwinis        ayiwin+N+I+Der/Dim+N+I+Sg
```

**Comment by Madoshakalaka** [comment]
However I have added an test case and referred to this issue in the lemma resolution process. Hopefully we have better way of dealing this in the future.

**Comment by eddieantonio** [comment]
A similar case exists for any NA/NI that has a **lexicallized** diminutive form; e.g.,

 - minôs -- cat
 - minôsis -- diminutive of cat OR kitten

**Comment by Madoshakalaka** [comment]
@eddieantonio currently fst does not analyze `minôsis` as a diminutive form of `minôs`. I'll add them to the integration test but skip the test for now.

**Comment by aarppe** [comment]
Some notes and observations.

1. _minôsis_ is not analyzed as a diminutive of _minôs_, because the latter is coded as a diminutive in the CW source, in which case the lemma is marked with a flag-diacritic in the stem LEXC file, which rules our further diminutivization. This is done automatically in the CW-to-LEXC code. Whether the coding is correct or not is another matter - here, the diminutivization concerns the purported French origin of _minôs_, namely _minou_, on which the diminutive suffix _-is_ is added. 

2. The coding of the plural form _ayiwinisa_ as a lemma would appear to be an error in the CW-to-LEXC conversion. Which explore eventually.
