### ISSUE TITLE
Present relabeled FST tags vertically (if the horizontal version does not fit the screen)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#250]
Now, the longer plain English relabelings of the linguistic breakdown expand horizontally beyond the screen boundary, cf.

![image](https://user-images.githubusercontent.com/15003407/74079096-dd7a1b80-49ef-11ea-90d7-5b68501b144f.png)

As an alternative, the linguistic breakdown should be presented vertically, perhaps with each feature and lemma/stem on its own line.

On a longer term, the presentation could be adjusted based on available screen size.

**Comment by Madoshakalaka** [comment]
following #251, it now adjusts based on available screen size. But I think the arrangement of the text still need some polish

**Comment by Madoshakalaka** [comment]
@aarppe I'll close this. Since adapting vertically is achieved now.

What isn't achieved is "better formatting", like presenting head, tail analyses on separate lines. This requirement is detailed in issue #209, and we have a [checkbox](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/209#issuecomment-581729948) for it
