### ISSUE TITLE
Extract latest new batch of Maskwacîs Cree recordings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#260]
This is a cross-over duplicate of https://github.com/UAlbertaALTLab/recording-validation-interface/issues/73#issuecomment-562206385

This is needed to expand the number of dictionary entries being linked with recordings.

**Comment by aarppe** [comment]
As discussed on 28.2., even if the extraction script doesn't work for all the new annotations, adding all new recordings snippets that can be easily done will improve the recording coverage of the new itwêwina.

**Comment by eddieantonio** [comment]
The latest batch has been imported! Now with a modest amount of new recordings. Please see attached file, or go to the secret link I sent you a while back.

[new-recordings.txt](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/files/4339800/new-recordings.txt)

**Comment by aarppe** [comment]
Ok - but now some words from the previous batch have disappeared, such as _wâpamêw_, at least from the list (via the link) but also live in itwêwina.

**Comment by eddieantonio** [comment]
Weird. I'll need to investigate.

**Comment by eddieantonio** [comment]
The reason is that I started the database from scratch, **deleting the speakers' info**. The search results only return recordings when the speakers' gender is known, but this data was deleted. I have added basic details for most of the speakers, though I think I missed some. Either way, the results are back!

https://sapir.artsrn.ualberta.ca/cree-dictionary/word/w%C3%A2pam%C3%AAw/
https://sapir.artsrn.ualberta.ca/cree-dictionary/word/s%C3%AEs%C3%AEp/
https://sapir.artsrn.ualberta.ca/cree-dictionary/word/mit%C3%B4n/

**Comment by aarppe** [comment]
Good. I think I provide that info on the speakers in late 2018 when you were setting up the first version of the validation interface. Are there any speakers for which the necessary info is missing?

Also, does the list on the link get updated as well? (because right now I can't wâpamêw there, with whatever spelling).

**Comment by eddieantonio** [comment]
The list in the link is live, though only wordforms that are spelled _exactly the same_ will match and be in the list. wâpamêw is spelled without diacritics in the recordings database, hence, it does not match with the dictionary database, but it's there. Thus, the dynamic list is a subset of available forms.
