### ISSUE TITLE
Inconsistent pages when no results are found

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#294]
Visiting `/search/poopoo` gives you the page with the welcoming message because no results are found.

While typing `poopoo` gives you a blank page.

It should be one way or another. Preferably, I think we need to inform the user with messages like "No search results found"

**Comment by eddieantonio** [comment]
@aarppe, I'm moving this one up the priority list because it's SUPER WEIRD when a search yields no results but all you see is the home page. Or the about page. Or a blank page. I think we'll stop a lot of confused feedback from the MESC folks just by addressing this early on.

Also, I imagine the fix _should_ be relatively simple. 🤞

**Comment by eddieantonio** [comment]
I'm going to make a results page for this!
