### ISSUE TITLE
Implement the FULL paradigms

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#357]
Right now we only have the basic paradigms, but we'd like the full paradigms, displaying over 500+ wordforms for VTA verbs!

We'll need to implement the More button, as well as make the full paradigm hidden by default.

We might want to implement #131 before we tackle this issue.

N.B.: revert 0520b97a4e2aec14c49030cde1ea194089b3f952 to get the PR for this one started!

**Comment by Madoshakalaka** [comment]
@eddieantonio Can I do this?

**Comment by eddieantonio** [comment]
Go for it!

**Comment by aarppe** [comment]
On the longer term, we'd like to implement this as a multipane solution (#167).

But since that will take time to implement, on the shorter term the first step could be just:

1. taking the current full paradigms
2. re-organizing the individual panes according to #131), and
3. possibly, but not necessarily, turning the full paradigms into a single column layout, in order to work best on mobile platforms.

**Comment by aarppe** [comment]
@Madoshakalaka is this still requiring further work, or is it just awaiting review (#461)?

**Comment by Madoshakalaka** [comment]
@aarppe there were more nuances to take care of. But I just finished them and it's currently waiting review. It should be online no later than today.

**Comment by Madoshakalaka** [comment]
@aarppe Please have a look

**Comment by aarppe** [comment]
@Madoshakalaka This is excellent!

I presume that editing the layout files will get automatically automatically propagated into itwêwina? There are some little organization fixes that should be done (by me) #131.
