### ISSUE TITLE
"Enable linguist mode" button

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#467]
Need to implement this or else @katieschmirler will cancel me.

Differences from "community mode":

 - [x] display text of word class abbreviations (e.g., VTA/VAI/VTI/NA/NAD, etc.) instead of emoji
 - [x] use linguistic labels in the paradigms
 - [ ] **EDIT**: word frequency in paradigms

Anything else @katieschmirler, @aarppe?

**Comment by katieschmirler** [comment]
Sounds good. But also cancelling is bad we don't do that.

**Comment by aarppe** [comment]
@eddieantonio What I have thought as the long term solution is allowing for an option or set of options (similar to the choice of orthography), on how the linguistic labeling is presented for a) the linguistic analysis, b) the lexical information (i.e. general word class and inflectional subcategory, so `VAI-1,` `NA-4w`), and c) the paradigm labeling.

I could see the following options below:
a. linguistic
b. plain English
c. (plain) nêhiyawêwin (this might require some further work in `crk.altlabel.tsv`)

The emojis could be a further (sub-)alternative (e.g. separately or for plain English and nêhiyawêwin), but could be combined with `a` (without emojis), `b` and `c` (with emojis):

Of course one could group some options together into modes, e.g. a community vs. academic/linguist mode, but I'm not entirely sure we'd actually need that.

A further option is interface language (English vs. nêhiyawêwina), but that can be kept separate from this issue.

**Comment by Madoshakalaka** [comment]
I like the idea of a linguistic mode.

**Comment by aarppe** [comment]
@eddieantonio this may be needed sooner rather than later, if the emojis are really an off-putting feature for (some) language instructors.

**Comment by eddieantonio** [comment]
Okay! I put this higher priority than observed wordform ranking.

**Comment by aarppe** [comment]
Some thoughts:

A. There could be two options for the linguistic mode in the search page.

The comparable case for the linguistic mode with 1-to-1 mapping would be (this mixes plain with linguistic labels):
1. VII, VAI, VTI, VTA, NA, NI, NAD, NID instead of the emojis 
2. Keeping 'like: X' (plain English) for the inflectional subcategory
3. Showing the long linguistic label in the pop-up, with the inflectional subcategory code in parentheses

For _mîcisow_, this would be (this uses only linguistic labels):
1. AI
2. like: nipâw
3: vowel-final animate intransitive verb (VAI-1)

Though, the even more compact alternative would be
4. The precise inflectional category as is (i.e. VAI-1, etc.)
5. Long linguistic relabeling in pop-up, without the inflectional subcategory code

For mîcisow, this would be:
4. VAI-1
5. vowel-final animate intransitive verb

B. In the paradigms, depending on the mode, the pop-up contents (which we haven't yet implemented) would rotate as in the old itwêwina. Anyhow, it would make sense to use the short linguistic labels for the sake of compactness in the paradigms, with the pop-up giving the long linguistic label. I would like also showing the plain English one in the pop-ups, as in the old itwêwina (but I'm wondering whether that takes up too much space, at least on a mobile device), e.g.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/15003407/86843876-6f9c5380-c064-11ea-9de7-7ac85f089f84.png">

**Comment by aarppe** [comment]
@eddieantonio Though we don't have nêhiyawêwin mode yet everywhere, but isn't that a separate issue?

**Comment by eddieantonio** [comment]
Indeed! nêhiyawêwin mode is #741
