### ISSUE TITLE
Split inflections with multiple possible forms over several lines

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#507]
e.g., instead of this

| Person | Form |
| - | - |
| we |	ninipânân | 
| you and we	| kinipânaw / kinipânânaw |

Let's have this:

| Person | Form |
| - | - |
| we |	ninipânân | 
| you and we	| kinipânaw |
| | kinipânânaw |

---

I know this was there before, but this is unsatisfying... I might need to make a new issue for this. Basically, an entirely new row should be made for any alternatives.

_Originally posted by @eddieantonio in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/pull/506_

**Comment by eddieantonio** [comment]
Here's me mocking up what it would look like by messing around with the devtools inspector:

![Screen Shot 2020-07-15 at 11 49 23 AM](https://user-images.githubusercontent.com/2294397/87578240-611bf080-c691-11ea-9332-28235ea2aa62.png) ![Screen Shot 2020-07-15 at 11 49 49 AM](https://user-images.githubusercontent.com/2294397/87578246-62e5b400-c691-11ea-88da-944d82424a6d.png)

**Comment by aarppe** [comment]
**Note also**: For "abstract" forms with multiple realizations, it might be that only one of those have been observed in corpora. Therefore, we should refine our paradigm presentation scheme so that only the actually attested and observed word-form is marked as such (bold-face or otherwise), not both/all. This is probably supported in practice by splitting those multiple forms each into their own cell.
