### ISSUE TITLE
Inflection typo

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/cree-intelligent-dictionary#573]
There seems to be a regression introduced recently for VII verbs in the obviative forms:

![screenshot 2020-12-02 at 21 32 04](https://user-images.githubusercontent.com/1033941/100968379-1686fd80-34e6-11eb-8d94-4ea2a59281d9.png)

`kiwêmakanyiw` should be `kiwêmakaniyiw`, etc. I'm *think* I checked this a week or so ago and it was correct?

**Comment by eddieantonio** [comment]
@atticusha @aarppe could you have a look?

**Comment by atticusha** [comment]
This has been fixed in the source code in a very ad hoc way. Basically, there was an error in the export of the source that has now been corrected. I've gone into `src/fst/stems/verb_stems.lexc` and changed all the errant VIIn that were classified as VIIw. This should fix these issues for now, but we will have to double check that no -n finals are in VIIw and vice versa when we re-export from source to our FST in the next update.

**Comment by aarppe** [comment]
To be explicit and for later reference, the error was in the coding in the original source, not in the importatation script. Anyhow, there's a temporary fix in the target LEXC code, but we need to make sure that the coding is fixed in the original source.
