### ISSUE TITLE
Excessive stemming (?) of English words in search and matching

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#788]
Trying out some searches, such as _Navajo_ or _waffle_, these are matched with preverbs/particles due to analyzing the English search word to consist of the roots/prefixes _na-_ and _wa-_, cf.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/15003407/117894434-8cec1080-b279-11eb-93c1-c279ba2bf3ec.png">

<img width="449" alt="image" src="https://user-images.githubusercontent.com/15003407/117894300-4c8c9280-b279-11eb-800e-e8dd12f1eae2.png">

**Comment by andrewdotn** [comment]
There was a bug since Januaryish where inputs with invalid symbols were getting analyzed up to the first invalid symbol. No `f` or `v` in Cree means `waffle` and `navajo` and `avocado` were getting analyzed as plain `wa` and `na` and `a`.

I guess nobody noticed since the search wasn’t good enough to play with, and the ranking wasn’t identifying that these apparently-high-quality results should go at the top of the result list.

Fixed by https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/pull/794
