### ISSUE TITLE
Typo in search yields nonsensical results

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/cree-intelligent-dictionary#897]
A search with a mis-spelled preverb shows some strange search results:

![screenshot 2021-07-06 at 20 47 34](https://user-images.githubusercontent.com/1033941/124697582-dcc30e80-de9b-11eb-92ba-ae9bec3231a8.png)

**Comment by eddieantonio** [comment]
ay-hay @aaronfay! We added a search query explainer so if you add `verbose:1` to a query, it will tell you some diagnostic information as to why it was ranked at the top. e.g., [`ê-pim-nêhiyawêyahk verbose:1`](https://itwewina.altlab.app/search?q=%C3%AA-pim-n%C3%AAhiyaw%C3%AAyahk%20verbose%3A1).

That being said, I have no idea why these are the results that it comes up with...

e.g., the first môswa has this as its verbose output:

```json
{
  "is_lemma": true,
  "wordform_length": 5,
  "target_language_keyword_match": [],
  "source_language_keyword_match": [],
  "morpheme_ranking": 7.50273,
  "cosine_vector_distance": 0.7475793659687042,
  "relevance_score": 0.0018667894933978996
}
```

**Comment by eddieantonio** [comment]
@aaronfay we've implemented two fixes for this:

 - English cosine vector search is no longer used if the query looks a lot like Cree (#903)
 - We updated the spell relax so that ê-pim- is analyzed as "ê-pimi-" (#904)

So you should now get reasonable results for this query! https://itwewina.altlab.app/search?q=%C3%AA-pim-n%C3%AAhiyaw%C3%AAyahk 🎉

**Comment by aaronfay** [comment]
Nice work @eddieantonio ⚡ ⚡ ⚡
