### ISSUE TITLE
Sort search results based on modified Levenshtein edit distance

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#96]
The search results should be ranked in order of [edit distance](https://en.wikipedia.org/wiki/Levenshtein_distance) from the query.

These distances should be calculated *after* the query is converted to SRO/circumflex.

 * An **exact match** will have a distance of 0, and should be ranked first.
 * An **addition**  should have a distance of 1: e.g., minôs vs. minôhs
 * A **deletion** should have a distance of 1: e.g., acâhkos vs. acâhko.
 * A **substitution** should have a distance of 1: e.g., ekwa vs. ikwa

Additionally, there should be "half" substitutions:
 * vowel lengths should incur a distance of ½
 * an 'h' in a rime should incur a distance of ½

Vowel length on "ê" vs "e" should count as a distance of 0.

**Comment by aarppe** [comment]
Some comments:

1. Would an exact match concern not just a lemma, but an inflected (i.e. such a form is written exactly according to the orthographical norm)? Even then one might want to order the results based on reverse corpus frequency for the lemma, unless we'd use a fully weighted analyzer FST.

2. Concerning the weights (for various orthographical edits), the error-correction model in the Giella infrastructure already has various specifications, cf. the following files:

ls tools/spellcheckers/fstbased/desktop/hfst/*.default.txt

3. Indeed, one could use the spell-checker version of the (H)FST, with 'hfst-ospell -S' to weight search results, when they don't exactly match with a search string. Interestingly, our collaborators at Carleton use this in their East Cree dictionary lookup. For instance:

hfst-ospell -S tools/spellcheckers/fstbased/desktop/hfst/crk.zhfst
acimew
"acimew" is NOT in the lexicon:
Corrections for "acimew":
âcimêw    5.079442
atimêw    13.079442
ahimêw    13.079442
akimêw    13.079442
âcimâw    15.079442
âcimow    15.079442
akimâw    23.079441
acimos    23.079441
aciyaw    23.079441
atimâw    23.079441

That allows even for the inclusion of word-form frequencies as part of the weighting of misspelling corrections.

Unfortunately, currently the Giella webpages describing error-correction weighting in full are only partially accessible due to a long-waited reorganization of their website. Nevertheless, one can take inspiration from the explicitly specified weights (and corrections).

**Comment by aarppe** [comment]
Within the Giella infrastructure, the following HFST command and specification appears to do the job in the case on single-character edit-distance:

`~/giella/giella-core/scripts/editdist.py -s -d 2 -w 10 --regex -i ~/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/editdist.default.txt > editdist.default.regex`

After this, you'd need to run the following compliation:

`hfst-regexp2fst -S -i editdist.default.regex -o editdist.default.hfst`

As for the multi-character string modifications (i.e. characters with context), the following seems to be a way to compile that:

hfst-strings2fst -i ~/giella/langs/crk/tools/spellcheckers/fstbased/desktop/hfst/strings.default.txt -o strings.default.hfst

What would yet be needed is adding Kleene stars at the beginning and end (and allowing this to take place twice), and then combining this with the single character edits.

Anyhow, taking the weights from editdist.default.txt and strings.default.txt used in the specification of the spell-checker error correction HFST model would be desirable, even if we're not explicitly using the Giella code itself.

**Comment by aarppe** [comment]
Couldn't resist fiddling with weighting edits:

```
[
  ! English interference
  d (->) t::0.0 ,, g (->) k::0.0 ,, j (->) c::0.0 ,,
  {iw} (->) {ow}::0.5 ,, {ow} (->) {iw}::0.5 ,,
  {tch} (->) c::0.0 ,, {ch} (->) c::0.0 ,, {ts} (->) c::0.5 ,,
  {ee} (->) [ i | î ]::0.0 ,, u (h) (->) a::0.0 ,,
  ! SRO-internal Orthographical variation in hyphenation
  [..] (->) %-::0.5 ,,
  ! Cree-internal perception
  e (->) ê::0.0 ,,
  a (->) â::0.25,, i (->) î::0.25 ,, o (->) ô::0.25 ,,
  â (->) a::0.5,, î (->) i::0.5 ,, ô (->) o::0.5 ,,
  [..] (->) h::0.5 || [ a | â | ê | i | î | o | ô ] _ [ c | k | p | t ] ,,
  h (->) 0::0.75 || [ a | â | ê | i | î | o | ô ] _ [ c | k | p | t ]
]
;
```

This can then be compiled with the following incantation:

`hfst-regexp2fst -S -i levenstein.hfscript -o levenstein.hfst
`
... and then composed together with a descriptive analyzer as follows:

`hfst-compose -F -1 levenstein.hfst -2 ../crk-anl-norm.hfst -o crk-anl-dw.hfst`

Then, one can see following weighted analyses:

```
nipihk
nipihk  nipiw+V+AI+Cnj+Prs+X    0.000000
nipihk  nipiy+N+I+Loc   0.250000
nipihk  nîpin+V+II+Cnj+Prs+3Sg 0.250000
nipihk  nîpiy+N+I+Loc  0.500000
nipihk  nipiw+V+AI+Imp+Imm+2Pl  0.750000
nipihk  nipiw+V+AI+Imp+Imm+2Pl  0.750000
nipihk  nipiw+V+AI+Imp+Imm+2Pl  0.750000
nipihk  nipiw+V+AI+Imp+Imm+2Pl  0.750000

acakos
acakos  acâhkos+N+A+Sg 0.750000
acakos  atâhk+N+A+Der/Dim+N+A+Sg       0.750000
acakos  ahcahk+N+A+Der/Dim+N+A+Sg       1.000000

uhcahkos
uhcahkos        ahcahk+N+A+Der/Dim+N+A+Sg       0.000000
uhcahkos        acâhkos+N+A+Sg 0.250000
uhcahkos        atâhk+N+A+Der/Dim+N+A+Sg       0.250000

neeyuh
neeyuh  niya+Pron+Pers+1Sg      0.000000



```

**Comment by aarppe** [comment]
The weighted spell-relax specification is now to be found in the appropriate location within the Giella infrastructure, namely:

`giella/langs/crk/src/orthography/spellrelax-weighted.regex `

**Comment by aarppe** [comment]
In addition to the above, we also need a weighted rule for the Plains Cree dialect marker, the accented y.

`y (->) ý::0.0`

This is now in` crk/src/orthography/spellrelax-weighted.regex`

**Comment by aarppe** [comment]
Note to selves - based on our discussions, this edit-distance scheme would in the first instance be primarily used for ranking Cree words matching with search strings.
